version: '3.9'
services:
  user_backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - users_db
      

  users_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata__:/var/lib/mysql


volumes:
  dbdata__:


      

